import react from "@vitejs/plugin-react-swc";
import { resolve } from "path";
import { defineConfig } from "vite";
import dts from "vite-plugin-dts";

export default defineConfig({
  plugins: [react()],
  build: {
    emptyOutDir: true,
    root: './',
    publicDir: 'public',
    rollupOptions: {
      input: resolve(__dirname, 'index.html'),
      output: {
        dir: 'dist',
        entryFileNames: 'assets/[name].[hash].js',
        assetFileNames: 'assets/[name].[hash][extname]',
        globals: {},
      },
      treeshake: true,
      external: [

        "@chaibuilder/runtime",
        "@floating-ui/dom",
        "@floating-ui/react-dom",
        "@mhsdesign/jit-browser-tailwindcss",
        "@radix-ui/react-accordion",
        "@radix-ui/react-alert-dialog",
        "@radix-ui/react-context-menu",
        "@radix-ui/react-dialog",
        "@radix-ui/react-dropdown-menu",
        "@radix-ui/react-hover-card",
        "@radix-ui/react-icons",
        "@radix-ui/react-label",
        "@radix-ui/react-menubar",
        "@radix-ui/react-navigation-menu",
        "@radix-ui/react-popover",
        "@radix-ui/react-scroll-area",
        "@radix-ui/react-select",
        "@radix-ui/react-separator",
        "@radix-ui/react-slot",
        "@radix-ui/react-switch",
        "@radix-ui/react-tabs",
        "@radix-ui/react-toast",
        "@radix-ui/react-toggle",
        "@radix-ui/react-tooltip",
        "@react-hookz/web",
        "react-arborist",
        "@react-email/render",
        "react-error-boundary",
        "sonner",
        "next-themes",
        "@rjsf/core",
        "@rjsf/utils",
        "@rjsf/validator-ajv8",
        "@tailwindcss/aspect-ratio",
        "@tailwindcss/forms",
        "@tailwindcss/line-clamp",
        "@tailwindcss/typography",
        "@tailwindcss/container-queries",
        "class-variance-authority",
        "@bobthered/tailwindcssPaletteGenerator",
        "clsx",
        "cmdk",
        "framer-motion",
        "date-fns",
        "flagged",
        "fuse.js",
        "himalaya",
        "tree-model",
        "i18next",
        "prop-types",
        "re-resizable",
        "lodash",
        "lucide-react",
        "react-autosuggest",
        "react-colorful",
        "react-frame-component",
        "react-hotkeys-hook",
        "react-i18next",
        "react-json-view",
        "@tiptap/react",
        "@tiptap/pm",
        "@tiptap/extension-link",
        "@tiptap/starter-kit",
        "@tiptap/extension-bubble-menu",
        "@tiptap/extension-underline",
        "@tiptap/extension-text-align",
        "react-wrap-balancer",
        "tailwind-merge",
        "tailwindcss-animate",
      ],
    },
  },
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
        secure: false,
      }
    }
  }
});
