name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      actions: write
      deployments: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.18.0

    - name: Install pnpm
      run: npm install -g pnpm@10.0.0

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Run Tests
      run: pnpm test

    - name: Build Project
      run: pnpm build
      env:
        VITE_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        VITE_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./dist

    - name: Deploy to Surge
      if: success()
      run: npx surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v4
      with:
        static_site_git_branch: gh-pages

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ github.token }}
        publish-dir: ./dist

    - name: Deploy to Vercel
      if: success()
      run: |
        npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_SCOPE }}
        npx vercel alias set ${{ secrets.VERCEL_PROJECT_ID }} ${{ secrets.VERCEL_ALIAS }}